# Generated by Django 3.2.4 on 2022-01-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_cashlog_createdby'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='restaurant',
            field=models.ManyToManyField(to='accounting.Restaurant'),
        ),
    ]
