version: "3.8"

services:
  web:
    container_name: dosbandidos
    build: ./
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    container_name: dosbandidos-db
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
