# Generated by Django 3.2.4 on 2021-10-11 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('supplier_type', models.CharField(choices=[('operationFood', 'Food'), ('operationLiquor', 'Liquor'), ('foodMisc', 'Food (Miscellaneous)'), ('liquorMisc', 'Liquor (Miscellaneous)'), ('labor', 'Labor'), ('service', 'Services'), ('uncategorized', 'Uncategorized')], max_length=20)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('supplier', models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='rule_supplier', to='accounting.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('initial_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_metric', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(choices=[(77, 'Order Count'), (76, 'Gross Sales'), (75, 'Labor')], on_delete=django.db.models.deletion.CASCADE, related_name='metric_supplier_name', to='accounting.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('initial_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_income', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_supplier_name', to='accounting.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('cost_center', models.CharField(choices=[('cash', 'Cash'), ('primaryAccount', 'Primary Account'), ('expensesAccount', 'Expenses Account'), ('notPaid', 'Not Paid'), ('standBy', 'Standby')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_expense', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_supplier_name', to='accounting.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='CashLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('card_auto_grat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('card_tips', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('modifications', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('comments', models.TextField(blank=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_cashlog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
