# Generated by Django 3.2 on 2021-04-30 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('supplierType', models.CharField(choices=[('operationFood', 'Food'), ('operationLiquor', 'Liquor'), ('foodMisc', 'Food (Miscellaneous)'), ('liquorMisc', 'Liquor (Miscellaneous)'), ('labor', 'Labor'), ('service', 'Services'), ('uncategorized', 'Uncategorized')], max_length=20)),
                ('isFixedExpense', models.BooleanField(default=False)),
                ('hasCredit', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('costCenter', models.CharField(choices=[('cash', 'Cash'), ('primaryAccount', 'Primary Account'), ('expensesAccount', 'Expenses Account'), ('notPaid', 'Not Paid')], max_length=20)),
                ('isPaid', models.BooleanField(default=True)),
                ('isCheck', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_name', to='accounting.supplier')),
            ],
        ),
    ]
