# Generated by Django 3.2 on 2021-04-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supplierType', models.CharField(choices=[('service', 'Service'), ('operation', 'Operation'), ('labor', 'Labor')], max_length=10)),
                ('isFixedExpense', models.BooleanField(default=False)),
                ('hasCredit', models.BooleanField(default=False)),
            ],
        ),
    ]
