# Generated by Django 3.2 on 2021-04-26 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplierType',
            field=models.CharField(choices=[('operationFood', 'Operation (Food)'), ('operationLiquor', 'Operation (Liquor)'), ('labor', 'Labor'), ('service', 'Service')], max_length=20),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('costCenter', models.CharField(choices=[('cash', 'Cash'), ('primaryAccount', 'Primary Bank Account'), ('expensesAccount', 'Expenses Bank Account')], max_length=20)),
                ('isPaid', models.BooleanField(default=True)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_name', to='accounting.supplier')),
            ],
        ),
    ]
