# Generated by Django 3.2 on 2021-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20210426_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='isCheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='costCenter',
            field=models.CharField(choices=[('cash', 'Cash'), ('primaryAccount', 'Primary Account'), ('expensesAccount', 'Expenses Account')], max_length=20),
        ),
    ]
