# Generated by Django 3.2 on 2021-04-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20210426_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
