# Generated by Django 3.2.8 on 2021-11-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20211114_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashlog',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_cashlog', to='accounting.restaurant'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_expense', to='accounting.restaurant'),
        ),
        migrations.AlterField(
            model_name='income',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_income', to='accounting.restaurant'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_metric', to='accounting.restaurant'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='supplier',
            field=models.ForeignKey(choices=[(77, 'Order Count'), (76, 'Gross Sales'), (75, 'Labor')], on_delete=django.db.models.deletion.CASCADE, related_name='metric_supplier_pk', to='accounting.supplier'),
        ),
    ]
