# Generated by Django 3.2 on 2021-05-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0005_auto_20210506_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='finishDate',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='income',
            name='initialDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('initialDate', models.DateField(blank=True, null=True)),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurant_metric', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(choices=[(77, 'Order Count'), (76, 'Gross Sales'), (75, 'Labor')], on_delete=django.db.models.deletion.CASCADE, related_name='metric_supplier_name', to='accounting.supplier')),
            ],
        ),
    ]
