# Generated by Django 3.2.4 on 2021-08-22 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='supplier_id',
        ),
        migrations.AddField(
            model_name='rule',
            name='supplier',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='rule_supplier', to='accounting.supplier'),
        ),
    ]
