# Generated by Django 3.2.4 on 2022-01-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_cashlog_restaurant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashlog',
            unique_together={('restaurant', 'date')},
        ),
    ]
