# Generated by Django 3.2.4 on 2021-09-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20210912_2120'),
    ]

    operations = [
        migrations.RenameField('supplier', 'supplierType', 'supplier_type'),
    ]
