# Generated by Django 3.2.4 on 2021-10-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20210912_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
